// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ldap.actions;

import ldap.ImportUserRecord;
import ldap.LdapException;
import ldap.LdapModule;
import ldap.ImportUserRecord.Result;
import ldap.proxies.LdapGroup;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.FeedbackHelper;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IFeedback.MessageType;
import com.mendix.systemwideinterfaces.core.UserAction;

public class ImportLdapGroups_Group extends UserAction<java.lang.Boolean>
{
	/** @deprecated use LdapServer.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __LdapServer;
	private final ldap.proxies.LdapServer LdapServer;
	private final java.lang.Boolean giveFeedbackToUser;

	public ImportLdapGroups_Group(
		IContext context,
		IMendixObject _ldapServer,
		java.lang.Boolean _giveFeedbackToUser
	)
	{
		super(context);
		this.__LdapServer = _ldapServer;
		this.LdapServer = _ldapServer == null ? null : ldap.proxies.LdapServer.initialize(getContext(), _ldapServer);
		this.giveFeedbackToUser = _giveFeedbackToUser;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
	    ILogNode log = Core.getLogger(LdapModule.LDAP_LOG);
		try {
			Result result = ImportUserRecord.runImportGroupsByGroup(this.LdapServer);
			
			if (this.giveFeedbackToUser) {
				if( result.hasImportErrors() ) 
				    FeedbackHelper.addTextMessageFeedback(this.getContext(), MessageType.ERROR, "An: " + (result.getImportError() != null ? result.getImportError().getMessage() : "(unknown)") + " error occured.  " + result.getStatistics(), true);
				else 
				    FeedbackHelper.addTextMessageFeedback(this.getContext(), MessageType.INFO, "Finished the group import", true);
			}
			
			FeedbackHelper.addRefreshClass(this.getContext(), LdapGroup.entityName);
			
			if( result.hasImportErrors() ) 
				return false;
		}
		catch (Exception le) {
			log.error("Failed to synchronize groups: " + le.getMessage(), le);
			if (this.giveFeedbackToUser) {
				FeedbackHelper.addTextMessageFeedback(this.getContext(), (le instanceof LdapException)?MessageType.WARNING:MessageType.ERROR, le.getMessage(), true);
			}
			return false;
		}
			
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ImportLdapGroups_Group";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
