// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ldap.actions;

import ldap.ImportUserRecord;
import ldap.ImportUserRecord.Result;
import ldap.LdapException;
import ldap.LdapModule;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IFeedback.MessageType;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.FeedbackHelper;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * imports users from the ldap store, as configured in the ldapserver
 */
public class ImportLdapUsers extends UserAction<java.lang.Boolean>
{
	/** @deprecated use ldapServer.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ldapServer;
	private final ldap.proxies.LdapServer ldapServer;

	public ImportLdapUsers(
		IContext context,
		IMendixObject _ldapServer
	)
	{
		super(context);
		this.__ldapServer = _ldapServer;
		this.ldapServer = _ldapServer == null ? null : ldap.proxies.LdapServer.initialize(getContext(), _ldapServer);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        ILogNode log = Core.getLogger(LdapModule.LDAP_LOG);
		try {
			Result result = null;
			
			if (ldapServer.getSynchronizationMethod() == ldap.proxies.SynchronizationMethod.SynchronizeByPath) {
				result = ImportUserRecord.runImportUsersByPath(this.ldapServer, null);
			} else if (ldapServer.getSynchronizationMethod() == ldap.proxies.SynchronizationMethod.SynchronizeByGroup){
				result = ImportUserRecord.runImportUsersByGroup(this.ldapServer, null);
			} else {
				String message = "No synchronization method specified for server: " + ldapServer.getDescription() + ".";
			    FeedbackHelper.addTextMessageFeedback(this.getContext(), MessageType.INFO, message, true);
			}
			
			if (result != null) {
				if( result.hasImportErrors() ) {
				    String message = "An: " + (result.getImportError() != null ? result.getImportError().getMessage() : "(unknown)") + " error occured.  " + result.getStatistics();
				    FeedbackHelper.addTextMessageFeedback(this.getContext(), MessageType.ERROR, message, true);
				    log.error(message);
				    return false;
				} else { 
				    FeedbackHelper.addTextMessageFeedback(this.getContext(), MessageType.INFO, result.getStatistics(), true);
				    log.info(result.getStatistics());
				}
			}
		}
		catch (Exception le) {
			log.error("Failed to synchronize users: " + le.getMessage(), le);
			FeedbackHelper.addTextMessageFeedback(this.getContext(), (le instanceof LdapException)?MessageType.WARNING:MessageType.ERROR, le.getMessage(), true);
			return false;
		}
			
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ImportLdapUsers";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
