// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ldap.actions;

import java.util.List;
import ldap.LdapModule;
import ldap.proxies.LdapGroup;
import ldap.proxies.LdapUser;
import system.proxies.User;
import system.proxies.UserRole;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import communitycommons.XPath;
import communitycommons.XPath.IBatchProcessor;
import com.mendix.systemwideinterfaces.core.UserAction;

public class ProcessGroupRoleChange extends UserAction<java.lang.Boolean>
{
	/** @deprecated use ldapGroup.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ldapGroup;
	private final ldap.proxies.LdapGroup ldapGroup;
	/** @deprecated use com.mendix.utils.ListUtils.map(addedRoles, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __addedRoles;
	private final java.util.List<system.proxies.UserRole> addedRoles;
	/** @deprecated use com.mendix.utils.ListUtils.map(removedRoles, com.mendix.systemwideinterfaces.core.IEntityProxy::getMendixObject) instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final java.util.List<IMendixObject> __removedRoles;
	private final java.util.List<system.proxies.UserRole> removedRoles;

	public ProcessGroupRoleChange(
		IContext context,
		IMendixObject _ldapGroup,
		java.util.List<IMendixObject> _addedRoles,
		java.util.List<IMendixObject> _removedRoles
	)
	{
		super(context);
		this.__ldapGroup = _ldapGroup;
		this.ldapGroup = _ldapGroup == null ? null : ldap.proxies.LdapGroup.initialize(getContext(), _ldapGroup);
		this.__addedRoles = _addedRoles;
		this.addedRoles = java.util.Optional.ofNullable(_addedRoles)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(addedRolesElement -> system.proxies.UserRole.initialize(getContext(), addedRolesElement))
			.collect(java.util.stream.Collectors.toList());
		this.__removedRoles = _removedRoles;
		this.removedRoles = java.util.Optional.ofNullable(_removedRoles)
			.orElse(java.util.Collections.emptyList())
			.stream()
			.map(removedRolesElement -> system.proxies.UserRole.initialize(getContext(), removedRolesElement))
			.collect(java.util.stream.Collectors.toList());
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext c = Core.createSystemContext(); //Context without transaction
		
		/** Process removed roles */
		for(final UserRole removedRole : this.removedRoles) {
			
			XPath.create(c, User.class)
				//For all users member of this group
				.eq(LdapUser.MemberNames.LdapUser_User, LdapUser.entityName, LdapUser.MemberNames.LdapUser_LdapGroup, this.ldapGroup)
				//..That have the role to be removed (should be all)
				.eq(User.MemberNames.UserRoles, removedRole)
				//..and have not
				.not()
					//..a group that
					.subconstraint(LdapUser.MemberNames.LdapUser_User, LdapUser.entityName, LdapUser.MemberNames.LdapUser_LdapGroup, LdapGroup.entityName)
						//.. provides the same role
						.eq(LdapGroup.MemberNames.Ldap_Role_Mapping, removedRole)
						//.. and is not group where are change
						.notEq(XPath.ID, this.ldapGroup)
					.close()
				.close()
				
				.batch(LdapModule.PAGE_SIZE, new IBatchProcessor<User>()
					{

						@Override
						public void onItem(User user, long offset, long total)
								throws Exception
						{
							List<UserRole> currentRoles = user.getUserRoles();
							currentRoles.remove(removedRole);
							user.setUserRoles(currentRoles);
							user.commit();
						}
					});
		}
		
		/** Process added roles */
		for(final UserRole addedRole : this.addedRoles) {
			XPath.create(c, User.class)
				//For all users member of this group
				.eq(LdapUser.MemberNames.LdapUser_User, LdapUser.entityName, LdapUser.MemberNames.LdapUser_LdapGroup, this.ldapGroup)
				//..That do not have this role
				.not()
					.eq(User.MemberNames.UserRoles, addedRole)
				.close()
				
				.batch(LdapModule.PAGE_SIZE, new IBatchProcessor<User>()
					{

						@Override
						public void onItem(User user, long offset, long total)
								throws Exception
						{
							List<UserRole> currentRoles = user.getUserRoles();
							currentRoles.add(addedRole);
							user.setUserRoles(currentRoles);
							user.commit();
						}
					});
		}
			
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ProcessGroupRoleChange";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
