// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ldap.actions;

import java.util.HashSet;
import java.util.Set;
import ldap.proxies.LookupUserAttr;
import ldap.proxies.LookupUserEntity;
import system.proxies.User;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.meta.IMetaObject;
import com.mendix.systemwideinterfaces.core.meta.IMetaPrimitive;
import communitycommons.XPath;
import communitycommons.XPath.IBatchProcessor;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

public class ReadSystemUserDerivates extends UserAction<java.lang.Boolean>
{
	public ReadSystemUserDerivates(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		IMetaObject systemUser = Core.getMetaObject(User.getType());
		
		/** Sync all entities */
		Set<String> entities = new HashSet<String>();
		entities.add(systemUser.getName());
		
		for(IMetaObject meta : Core.getMetaObjects()) 
			if (meta.getSuperObjects().contains(systemUser)) 
				entities.add(meta.getName());
		
		XPath.create(getContext(), LookupUserEntity.class).syncDatabaseWithCollection(entities, LookupUserEntity.MemberNames.Name, true);
		
		/** Sync all attributes */
		XPath.create(getContext(), LookupUserEntity.class).batch(1000, new IBatchProcessor<LookupUserEntity>()
			{

				@Override
				public void onItem(LookupUserEntity e, long offset, long total) throws CoreException
				{
					IMetaObject entity = Core.getMetaObject(e.getName());
					Set<String> attributes = new HashSet<String>();
					
					for(IMetaPrimitive field : entity.getMetaPrimitives())
						if (field.getType().equals(IMetaPrimitive.PrimitiveType.String) && !field.getName().equals(User.MemberNames.Name)) //not name, is used as login field 
							attributes.add(field.getName());
					
					//Sync attritubes
					XPath.create(e.getContext(), LookupUserAttr.class).syncDatabaseWithCollection(attributes, LookupUserAttr.MemberNames.Name, true, 
							LookupUserAttr.MemberNames.LookupUserAttr_LookupUserEntity, e);
				}
			});
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ReadSystemUserDerivates";
	}

	// BEGIN EXTRA CODE
	
	// END EXTRA CODE
}
