// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ldap.actions;

import java.util.List;
import ldap.LdapModule;
import ldap.proxies.LookupLdapAttr;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IFeedback.MessageType;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import communitycommons.XPath;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.FeedbackHelper;
import com.mendix.systemwideinterfaces.core.UserAction;

public class ReadLdapDirectoryAttributes extends UserAction<java.lang.Boolean>
{
	/** @deprecated use ldapServer.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ldapServer;
	private final ldap.proxies.LdapServer ldapServer;

	public ReadLdapDirectoryAttributes(
		IContext context,
		IMendixObject _ldapServer
	)
	{
		super(context);
		this.__ldapServer = _ldapServer;
		this.ldapServer = _ldapServer == null ? null : ldap.proxies.LdapServer.initialize(getContext(), _ldapServer);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        ILogNode log = Core.getLogger(LdapModule.LDAP_LOG);
		
		try {
			List<String> attrs = LdapModule.getInstance().getLdapUserAttributes(this.getContext(), this.ldapServer);
			if (attrs == null || attrs.size() == 0)
			    FeedbackHelper.addTextMessageFeedback(this.getContext(), MessageType.WARNING, "Failed to find any attributes. Please enter attribute names manually", true);
				
			else //Sync collection
				XPath.create(Core.createSystemContext(), LookupLdapAttr.class).syncDatabaseWithCollection(attrs, LookupLdapAttr.MemberNames.Name, true, 
						LookupLdapAttr.MemberNames.LookupLdapAttr_LdapServer, this.ldapServer);
			
			FeedbackHelper.addRefreshClass(this.getContext(), LookupLdapAttr.getType());
		}
		catch(Exception e) {
			log.warn("Failed to read attributes: " + e.getMessage(), e);
			throw e;
		}
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ReadLdapDirectoryAttributes";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
