// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ldap.actions;

import java.util.List;
import ldap.ImportUserRecord;
import ldap.ImportUserRecord.Result;
import ldap.proxies.LdapServer;
import ldap.proxies.ServerConfigType;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IContext;
import communitycommons.XPath;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * This microflow + java action will sync a single user name against all Ldap servers. This is useful for instance when you want to update a single user's data in a login handler. Calling this microflow by name from Java can create a runtime dependency, instead of a compile-time one.
 * Be careful when changin the name or signature of this microflow, other app store modules might depend on it.
 */
public class SyncSingleUser extends UserAction<java.lang.Boolean>
{
	private final java.lang.String Username;

	public SyncSingleUser(
		IContext context,
		java.lang.String _username
	)
	{
		super(context);
		this.Username = _username;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        log.trace("Retrieving LDAP servers");
        List<LdapServer> servers = XPath.create(this.getContext(), LdapServer.class)
                .eq(LdapServer.MemberNames.Enabled, true).all();
        log.trace(servers.size() + " servers found");
        for (LdapServer server : servers) {
            log.trace("Syncing user '" + Username + "' on server '"
                    + server.getDescription() + "'");
            if (server.getServerConfigType() == ServerConfigType.CreateDuringSync) {
                Result r = ImportUserRecord.runImportUsersByPath(server, Username);
                if (r.hasImportErrors())
                    throw r.getImportError();
            }
        }
        log.trace("Done syncing user '" + Username + "'");
        
        return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SyncSingleUser";
	}

	// BEGIN EXTRA CODE
    private final static ILogNode log = Core.getLogger("Ldap");
	// END EXTRA CODE
}
