// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ldap.actions;

import ldap.LdapException;
import ldap.LdapModule;
import ldap.TestImportItems;
import ldap.proxies.TestEntry;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IFeedback.MessageType;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.FeedbackHelper;
import com.mendix.systemwideinterfaces.core.UserAction;

public class TestImportAllObjectsAndAttributes extends UserAction<java.lang.Boolean>
{
	/** @deprecated use LdapServerSelection.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __LdapServerSelection;
	private final ldap.proxies.LdapServer LdapServerSelection;

	public TestImportAllObjectsAndAttributes(
		IContext context,
		IMendixObject _ldapServerSelection
	)
	{
		super(context);
		this.__LdapServerSelection = _ldapServerSelection;
		this.LdapServerSelection = _ldapServerSelection == null ? null : ldap.proxies.LdapServer.initialize(getContext(), _ldapServerSelection);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        ILogNode log = Core.getLogger(LdapModule.LDAP_LOG);
		try {
		    FeedbackHelper.addTextMessageFeedback(this.getContext(), MessageType.INFO, TestImportItems.runImport(this.LdapServerSelection), true);
		}
		catch (Exception le) {
			log.error("Failed to synchronize users: " + le.getMessage(), le);
			FeedbackHelper.addTextMessageFeedback(this.getContext(), (le instanceof LdapException)?MessageType.WARNING:MessageType.ERROR, le.getMessage(), true);
		}
		FeedbackHelper.addRefreshClass(this.getContext(), TestEntry.getType());
			
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "TestImportAllObjectsAndAttributes";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
