// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ldap.actions;

import ldap.LdapModule;
import com.mendix.systemwideinterfaces.core.AuthenticationRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class TestLdapAuthentication extends UserAction<java.lang.Boolean>
{
	/** @deprecated use LDAPServer.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __LDAPServer;
	private final ldap.proxies.LdapServer LDAPServer;
	private final java.lang.String UserName;
	private final java.lang.String Password;

	public TestLdapAuthentication(
		IContext context,
		IMendixObject _lDAPServer,
		java.lang.String _userName,
		java.lang.String _password
	)
	{
		super(context);
		this.__LDAPServer = _lDAPServer;
		this.LDAPServer = _lDAPServer == null ? null : ldap.proxies.LdapServer.initialize(getContext(), _lDAPServer);
		this.UserName = _userName;
		this.Password = _password;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		if ( !LdapModule.getInstance().authenticateUser(this.getContext(), LDAPServer, this.UserName, this.Password, true) ) {
			throw new AuthenticationRuntimeException("LdapLogin FAILED: invalid password for user " + this.UserName);
		}
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "TestLdapAuthentication";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
