// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ldap.actions;

import ldap.LdapException;
import ldap.LdapModule;
import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.core.IFeedback.MessageType;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.FeedbackHelper;
import com.mendix.systemwideinterfaces.core.UserAction;

public class TestLdapConnection extends UserAction<java.lang.Boolean>
{
	/** @deprecated use ldapServer.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ldapServer;
	private final ldap.proxies.LdapServer ldapServer;

	public TestLdapConnection(
		IContext context,
		IMendixObject _ldapServer
	)
	{
		super(context);
		this.__ldapServer = _ldapServer;
		this.ldapServer = _ldapServer == null ? null : ldap.proxies.LdapServer.initialize(getContext(), _ldapServer);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
        ILogNode log = Core.getLogger(LdapModule.LDAP_LOG);
		try {
			LdapModule.getInstance().testConnection(this.getContext(), this.ldapServer);
			FeedbackHelper.addTextMessageFeedback(this.getContext(), MessageType.INFO, "Connection established", true);
			return true;
		}
		catch (Throwable le) {
			log.warn("Failed to connect to " + this.ldapServer.getServerAddress() + ": " + le.getMessage(), le);
			FeedbackHelper.addTextMessageFeedback(this.getContext(), (le instanceof LdapException)?MessageType.WARNING:MessageType.ERROR, le.getMessage(), true);
			return false;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "TestLdapConnection";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
