// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import java.security.interfaces.ECPrivateKey;
import java.security.interfaces.ECPublicKey;
import java.security.interfaces.RSAPrivateKey;
import java.security.interfaces.RSAPublicKey;
import java.util.List;
import java.util.*;
import com.auth0.jwt.JWT;
import com.auth0.jwt.JWTCreator.Builder;
import com.auth0.jwt.algorithms.Algorithm;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.nimbusds.jose.jwk.ECKey;
import com.nimbusds.jose.jwk.JWK;
import com.nimbusds.jose.jwk.RSAKey;
import oidc.implementation.MxOIDCHandler;
import oidc.implementation.common.Constants;
import oidc.implementation.security.KeyStoreHelper;
import oidc.implementation.security.SecurityHelper;
import oidc.proxies.Audience;
import com.mendix.systemwideinterfaces.core.UserAction;

public class GenerateJWT extends UserAction<java.lang.String>
{
	/** @deprecated use ClientConfiguration.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __ClientConfiguration;
	private final oidc.proxies.ClientConfiguration ClientConfiguration;
	private final oidc.proxies.ENU_SigningAlgorithm algorithm;
	/** @deprecated use jwt.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __jwt;
	private final oidc.proxies.JWT jwt;

	public GenerateJWT(
		IContext context,
		IMendixObject _clientConfiguration,
		java.lang.String _algorithm,
		IMendixObject _jwt
	)
	{
		super(context);
		this.__ClientConfiguration = _clientConfiguration;
		this.ClientConfiguration = _clientConfiguration == null ? null : oidc.proxies.ClientConfiguration.initialize(getContext(), _clientConfiguration);
		this.algorithm = _algorithm == null ? null : oidc.proxies.ENU_SigningAlgorithm.valueOf(_algorithm);
		this.__jwt = _jwt;
		this.jwt = _jwt == null ? null : oidc.proxies.JWT.initialize(getContext(), _jwt);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		JWK jwkObj = MxOIDCHandler.getInstance().getJWK(ClientConfiguration,getContext());
		Algorithm alg = new SecurityHelper().getAlgorithm(algorithm,jwkObj);
		List<IMendixObject> audiences = Core.retrieveByPath(getContext(),
				jwt.getMendixObject(), oidc.proxies.Audience.MemberNames.Audience_JWT.toString());

		String[] auds = new String[audiences.size()];
		{
			int i = 0;
			for (IMendixObject audienceObj : audiences) {
				Audience aud = Audience.initialize(getContext(), audienceObj);
				auds[i] = aud.getaud();
				i++;
			}
		}

		Builder builder = JWT.create();
		if (jwt.getexp() != null) builder.withExpiresAt(jwt.getexp());
		if (jwt.getiss() != null && !jwt.getiss().isBlank()) builder.withIssuer(jwt.getiss());
		if (jwt.getjti() != null && !jwt.getjti().isBlank()) builder.withJWTId(jwt.getjti());
		if (jwt.getkid() != null && !jwt.getkid().isBlank()) builder.withKeyId(jwt.getkid());
		if (jwt.getsub() != null && !jwt.getsub().isBlank()) builder.withSubject(jwt.getsub());
		if (auds.length > 0) builder.withAudience(auds);
		Map<String, Object> headers = new HashMap<String, Object>();
		headers.put("kid", jwt.getkid());
		builder.withHeader(headers);
		return builder.sign(alg);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateJWT";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
