// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package businessevents.actions;

import com.mendix.databroker.factories.EventConsumerFactory;
import com.mendix.databroker.services.SubscriptionService;
import com.mendix.databroker.utils.ConfigurationProvider;
import com.mendix.databroker.utils.CoreProxyImpl;
import com.mendix.databroker.utils.ExceptionLogger;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * This java action starts the subscription to consume a business event from the server/channel configured in the BusinessEvents module constants.
 * 
 * Service name: Name of the service or source system that creates the business events.
 * 
 * Event name: Name of the business event your application should receive.
 * 
 * Event handler: Microflow to process the received event.
 * 
 * Subscribe from beginning: Boolean to determine if you want to receive all the available events (including those sent in the last 7 days) or only new events?
 * 
 * NOTE
 * The ShutdownBusinessEvent action should be configured to be run before shutdown when using this action. This can be done by configuring the BusinessEvents.BSd_ShutdownSubscribers microflow to be called.
 */
public class ConsumeBusinessEvent extends UserAction<java.lang.Void>
{
	private final java.lang.String ServiceName;
	private final java.lang.String Channel;
	private final java.lang.String EventName;
	private final java.lang.String EventHandler;
	private final java.lang.Boolean SubscribeFromBeginning;

	public ConsumeBusinessEvent(
		IContext context,
		java.lang.String _serviceName,
		java.lang.String _channel,
		java.lang.String _eventName,
		java.lang.String _eventHandler,
		java.lang.Boolean _subscribeFromBeginning
	)
	{
		super(context);
		this.ServiceName = _serviceName;
		this.Channel = _channel;
		this.EventName = _eventName;
		this.EventHandler = _eventHandler;
		this.SubscribeFromBeginning = _subscribeFromBeginning;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		CoreProxyImpl coreProxy = CoreProxyImpl.INSTANCE;
		try {
			ConfigurationProvider configProvider = new ConfigurationProvider(coreProxy);
			SubscriptionService subscriptionService = SubscriptionService.Companion.instantiateSubscriptionService(
					configProvider,
					getContext(),
					coreProxy,
					EventConsumerFactory.EventConsumerFactoryImpl.INSTANCE
			);
			subscriptionService.registerSubscription(ServiceName, Channel, EventName, EventHandler, SubscribeFromBeginning);
		} catch (Exception exception) {
			ExceptionLogger.INSTANCE.logBusinessEventsException(exception, coreProxy);
			throw exception;
		}
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "ConsumeBusinessEvent";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
