// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package businessevents.actions;

import com.mendix.databroker.utils.CoreProxyImpl;
import com.mendix.databroker.utils.exceptions.OutboxException;
import com.mendix.logging.LogLevel;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

public class DeleteOutboxItem extends UserAction<java.lang.Void>
{
	/** @deprecated use Outbox.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __Outbox;
	private final businessevents.proxies.Outbox Outbox;

	public DeleteOutboxItem(
		IContext context,
		IMendixObject _outbox
	)
	{
		super(context);
		this.__Outbox = _outbox;
		this.Outbox = _outbox == null ? null : businessevents.proxies.Outbox.initialize(getContext(), _outbox);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		final  var outboxMendixObject = Outbox.getMendixObject();
		var coreProxy = CoreProxyImpl.INSTANCE;
		var context = coreProxy.createSystemContext();
		if(outboxMendixObject == null){
			throw new OutboxException("Attempted to delete an Outbox item but did not pass an Outbox object\"");
		}
		var deleteOutbox = coreProxy.delete(context, outboxMendixObject);
		if(deleteOutbox){
			coreProxy.getLogger().log(LogLevel.DEBUG, String.format("Outbox item with EventId %s successfully deleted.\"", outboxMendixObject.getMember("EventId").getValue(context)));
		}else{
			throw new OutboxException(String.format("Outbox item with EventId %s failed to delete.\"", outboxMendixObject.getMember("EventId").getValue(context)));
		}
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "DeleteOutboxItem";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
