// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package businessevents.actions;

import com.mendix.databroker.services.ProducerService;
import com.mendix.databroker.utils.ConfigurationProvider;
import com.mendix.databroker.utils.CoreProxyImpl;
import com.mendix.databroker.utils.ExceptionLogger;
import com.mendix.logging.LogLevel;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * This java action publishes the business event to the server/channel configured in the BusinessEvents module constants. After publishing other applications will be able to consume the event.
 * 
 * Service name: Specify the name for the Business Event service. If left empty a default service name is added: `Project-Id.EntityName`.
 *  
 * Subject: Subject of the business event. Subject can be anything you consider useful, it’s like a short description of what can be expected in the payload, similar to email subject. It will help subscribed apps decide if the event might be useful to them.
 * 
 * Event name: Name of the business event. If empty then it will be set to entity name.
 * 
 * Event Data: The entity that you want to publish in the service that will represent the Business event in the subscribers app. This should an entity that you have configured to inherit from the `BusinessEvent`.
 * 
 * NOTE
 * This java action will commit all event objects at the start of the publishing process. In case something goes wrong during the publishing process a retry mechanism will be triggered for up to 48 hours. Once a retry is successful a second commit happens to the business event object to update the `EventId` and `PublishedTimestamp` attributes.
 */
public class PublishBusinessEvent extends UserAction<java.lang.Void>
{
	private final java.lang.String ServiceName;
	private final java.lang.String Source;
	private final java.lang.String Channel;
	private final com.mendix.systemwideinterfaces.javaactions.parameters.IStringTemplate Subject;
	private final java.lang.String EventName;
	/** @deprecated use BusinessEvent.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __BusinessEvent;
	private final businessevents.proxies.PublishedBusinessEvent BusinessEvent;

	public PublishBusinessEvent(
		IContext context,
		java.lang.String _serviceName,
		java.lang.String _source,
		java.lang.String _channel,
		com.mendix.systemwideinterfaces.javaactions.parameters.IStringTemplate _subject,
		java.lang.String _eventName,
		IMendixObject _businessEvent
	)
	{
		super(context);
		this.ServiceName = _serviceName;
		this.Source = _source;
		this.Channel = _channel;
		this.Subject = _subject;
		this.EventName = _eventName;
		this.__BusinessEvent = _businessEvent;
		this.BusinessEvent = _businessEvent == null ? null : businessevents.proxies.PublishedBusinessEvent.initialize(getContext(), _businessEvent);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		final var businessEventMendixObject = BusinessEvent.getMendixObject();
		final var SOURCE_NAME = "SourceName";
		CoreProxyImpl coreProxy = CoreProxyImpl.INSTANCE;
		if (this.BusinessEvent != null) {
			businessEventMendixObject.setValue(getContext(), "ServiceName", this.ServiceName);
			// only set SourceName from Source if it is not filled on the entity
			if (businessEventMendixObject.<String>getValue(getContext(), SOURCE_NAME) == null || businessEventMendixObject.<String>getValue(getContext(), SOURCE_NAME).isEmpty())
				businessEventMendixObject.setValue(getContext(), SOURCE_NAME, this.Source);
			businessEventMendixObject.setValue(getContext(), "Channel", this.Channel);
			businessEventMendixObject.setValue(getContext(), "EventName", this.EventName);
			businessEventMendixObject.setValue(getContext(), "Subject", this.Subject.toString());
			try {
				ConfigurationProvider configurationProvider = new ConfigurationProvider(coreProxy);
				ProducerService producerService = new ProducerService(configurationProvider, coreProxy);
				producerService.schedulePublish(businessEventMendixObject, getContext());
			} catch (Exception exception) {
				ExceptionLogger.INSTANCE.logBusinessEventsException(exception, coreProxy);
				throw exception;
			}
		} else {
			String errorMessage = String.format("Empty object received for publishing %s event", this.EventName);
			coreProxy.getLogger().log(LogLevel.ERROR, errorMessage);
		}

		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PublishBusinessEvent";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
