// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package businessevents.actions;

import com.mendix.databroker.utils.CoreProxyImpl;
import com.mendix.logging.LogLevel;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * This java action publishes a business event according to the published business event service document in which the entity passed as parameter here is configured.
 * 
 * Subject: Subject of the business event. Subject can be anything you consider useful, it’s like a short description of what can be expected in the payload, similar to email subject. It will help subscribed apps decide if the event might be useful to them.
 * 
 * Event Data: The entity that you want to publish. This should be an entity that you have configured to inherit from the `BusinessEvent`.
 * 
 * NOTE
 * This java action will commit all event objects at the start of the publishing process. In case something goes wrong during the publishing process a retry mechanism will be triggered for up to 48 hours. Once a retry is successful a second commit happens to the business event object to update the `EventId` and `PublishedTimestamp` attributes.
 */
public class PublishBusinessEvent_V2 extends UserAction<java.lang.Void>
{
	private final com.mendix.systemwideinterfaces.javaactions.parameters.IStringTemplate Subject;
	/** @deprecated use BusinessEvent.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __BusinessEvent;
	private final businessevents.proxies.PublishedBusinessEvent BusinessEvent;

	public PublishBusinessEvent_V2(
		IContext context,
		com.mendix.systemwideinterfaces.javaactions.parameters.IStringTemplate _subject,
		IMendixObject _businessEvent
	)
	{
		super(context);
		this.Subject = _subject;
		this.__BusinessEvent = _businessEvent;
		this.BusinessEvent = _businessEvent == null ? null : businessevents.proxies.PublishedBusinessEvent.initialize(getContext(), _businessEvent);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		CoreProxyImpl.INSTANCE.getLogger().log(LogLevel.ERROR,
				"This java action should be replaced build time by the extension and therefore never run");
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PublishBusinessEvent_V2";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
