// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package businessevents.actions;

import com.mendix.databroker.services.ProducerService;
import com.mendix.databroker.utils.ConfigurationProvider;
import com.mendix.databroker.utils.CoreProxyImpl;
import com.mendix.databroker.utils.ExceptionLogger;
import com.mendix.logging.LogLevel;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.systemwideinterfaces.core.UserAction;

/**
 * Action responsible for publishing the entity to Kafka.
 */
public class PublishEvents extends UserAction<java.lang.Void>
{
	/** @deprecated use BusinessEvent.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __BusinessEvent;
	private final businessevents.proxies.Outbox BusinessEvent;

	public PublishEvents(
		IContext context,
		IMendixObject _businessEvent
	)
	{
		super(context);
		this.__BusinessEvent = _businessEvent;
		this.BusinessEvent = _businessEvent == null ? null : businessevents.proxies.Outbox.initialize(getContext(), _businessEvent);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		final var businessEventMendixObject = BusinessEvent.getMendixObject();
		CoreProxyImpl coreProxy = CoreProxyImpl.INSTANCE;
		if (this.BusinessEvent != null) {
			try {
				ConfigurationProvider configurationProvider = new ConfigurationProvider(coreProxy);
				ProducerService producerService = new ProducerService(configurationProvider, coreProxy);
				producerService.sendEvent(businessEventMendixObject);
			} catch (Exception exception) {
				ExceptionLogger.INSTANCE.logBusinessEventsException(exception, coreProxy);
				throw exception;
			}
		} else {
			coreProxy.getLogger().log(LogLevel.ERROR, "Empty object received for publishing event");
		}
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PublishEvents";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
