// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package businessevents.actions;

import com.mendix.databroker.services.StartupService;
import com.mendix.databroker.utils.ConfigurationProvider;
import com.mendix.databroker.utils.CoreProxyImpl;
import com.mendix.logging.LogLevel;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;

public class StartupBusinessEvents extends UserAction<java.lang.Void>
{
	public StartupBusinessEvents(IContext context)
	{
		super(context);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		CoreProxyImpl coreProxy = CoreProxyImpl.INSTANCE;
		var configurationProvider = new ConfigurationProvider(coreProxy);
		var logNode = coreProxy.getLogger();
		StartupService.INSTANCE.init(configurationProvider, coreProxy);
		logNode.log(LogLevel.INFO, "Business events started successfully");
		var moduleMode = configurationProvider.getModuleRunningMode();
		logNode.log(LogLevel.INFO, moduleMode);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "StartupBusinessEvents";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
